name: Matrix Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        # github actions will run this for each os listed in operating-system when we use this matrix approach
        # runs for each possible combination of values that using in the steps.

        include: # include specific configs, add standalone combos, (instead of every matrix config)
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }} # same here it will run for each node version.
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build